### ISSUE TITLE
Update METbaseimage to complete the transition to the Debian base image

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METbaseimage#12]
## Describe the New Feature ##
dtcenter/MET#2669 adds a new dependency on the Proj library (recommend using the latest Proj version 9.2.1).

This issue is to update the METbaseimage to include the proj libraries to facilitate the compilation of MET for GitHub actions. This can be accomplished as follows:
1. Update METbaseimage to fully switch over to the Debian base image. That version is currently available on DockerHub as `dtcenter/met-base:v2.0_debian`. And we've been using that base image for MET development for > 6 months.
2. Complete the transition by
  - Replacing `Dockerfile` with the contents of `Dockerfile.debian`
  - Replace `Dockerfile.debian_unit_test_env` with the contents of `Dockerfile.unit_test_env`
  - Updating the file names used in the GHA job
3. Make sure that MET's `compile_MET_all.sh` script and corresponding tar file has been updated to support the compilation of Proj. Note that dtcenter/METbaseimage#13 will soon add support for ecKit and Atlas.
4. Tag this repository with version 2.1 which will push a new METbaseimage version.

Including this issue on the `MET-12.0.0 Development` project since this change relates directly to the compilation of MET. 

### Acceptance Testing ###
Verify that the development version of MET can compile with these changes.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.

### Relevant Deadlines ###
Please do as early as possible in the MET version 12.0.0 development timeline.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by climbfuji** [comment]
Maybe you want to look into spack to build the dependencies for MET? Our spack-stack project could be very helpful in that regard.

**Comment by JohnHalleyGotway** [comment]
Thanks @climbfuji for the info on this. I did coordinate with @jprestop about Spack. I do suspect that using Spack would be an alternative to the `compile_MET_all.sh` script that lives in the MET repository. The Dockerfile in this repo pulls that script and compiles the dependent libraries. So if we pursue a Spack solution, presumably we'd call that in this context rather than that compilation script.
