### ISSUE TITLE
Bugfix: Cannot install METplus package using v1.1

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METbaseimage#5]
An error is now occurring when trying to install METplus:
https://github.com/dtcenter/METplus/runs/8309144269?check_suite_focus=true#step:4:229
This was not immediately obvious when we switched to the new base image because a failure in the docker build step for METplus was not captured.

## Describe the Problem ##

This [StackOverflow thread](https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul) suggests installing libffi-devel via `yum install libffi-devel` before installing Python3 should fix the issue.

### Expected Behavior ###
Should be able to install METplus as a package without error

### Environment ###
Describe your runtime environment:
*1. Machine: Docker container dtcenter/met-base:v1.1 based on centos:latest*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Start met-base:v1.1 container*
*2. Clone METplus repository*
*3. cd METplus*
*4. Checkout develop branch `git checkout develop`*
*5. Run `python3 setup.py install`*
*6. Should see error relating to _ctypes*

### Relevant Deadlines ###
ASAP

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by jprestop** [comment]
@georgemccabe Tested a fix for this locally.  I made the changes directly in main, re-tagged, and re-released.
